### ISSUE TITLE
Materials don't apply to vehicle when exporting to C2

### ISSUE THREAD

**Issue by Razor792** [ErrolErrolson/Flummery#62]
Materials don't load up in PT2 when exporting a vehicle (TDR2000 imported vehicle tested) into Flummery and saving for C2.
Materials seem to be referenced fine in the Materials window but they don't apply to the vehicle.

**Comment by ErrolErrolson** [comment]
Closed by 3bbc993d16d4e85485d3a4e65a3e6d93d510dbb8
